-- Table: public.gedi_4a_data_complete

-- DROP TABLE public.gedi_4a_data_complete;

CREATE TABLE IF NOT EXISTS public.gedi_4a_data_complete
(
    agbd real,
    agbd_pi_lower real,
    agbd_pi_upper real,
    agbd_a1 real,
    agbd_a10 real,
    agbd_a2 real,
    agbd_a3 real,
    agbd_a4 real,
    agbd_a5 real,
    agbd_a6 real,
    agbd_pi_lower_a1 real,
    agbd_pi_lower_a10 real,
    agbd_pi_lower_a2 real,
    agbd_pi_lower_a3 real,
    agbd_pi_lower_a4 real,
    agbd_pi_lower_a5 real,
    agbd_pi_lower_a6 real,
    agbd_pi_upper_a1 real,
    agbd_pi_upper_a10 real,
    agbd_pi_upper_a2 real,
    agbd_pi_upper_a3 real,
    agbd_pi_upper_a4 real,
    agbd_pi_upper_a5 real,
    agbd_pi_upper_a6 real,
    agbd_se_a1 real,
    agbd_se_a10 real,
    agbd_se_a2 real,
    agbd_se_a3 real,
    agbd_se_a4 real,
    agbd_se_a5 real,
    agbd_se_a6 real,
    agbd_t_a1 real,
    agbd_t_a10 real,
    agbd_t_a2 real,
    agbd_t_a3 real,
    agbd_t_a4 real,
    agbd_t_a5 real,
    agbd_t_a6 real,
    agbd_t_pi_lower_a1 real,
    agbd_t_pi_lower_a10 real,
    agbd_t_pi_lower_a2 real,
    agbd_t_pi_lower_a3 real,
    agbd_t_pi_lower_a4 real,
    agbd_t_pi_lower_a5 real,
    agbd_t_pi_lower_a6 real,
    agbd_t_pi_upper_a1 real,
    agbd_t_pi_upper_a10 real,
    agbd_t_pi_upper_a2 real,
    agbd_t_pi_upper_a3 real,
    agbd_t_pi_upper_a4 real,
    agbd_t_pi_upper_a5 real,
    agbd_t_pi_upper_a6 real,
    agbd_t_se_a1 real,
    agbd_t_se_a10 real,
    agbd_t_se_a2 real,
    agbd_t_se_a3 real,
    agbd_t_se_a4 real,
    agbd_t_se_a5 real,
    agbd_t_se_a6 real,
    algorithm_run_flag_a1 bigint,
    algorithm_run_flag_a10 bigint,
    algorithm_run_flag_a2 bigint,
    algorithm_run_flag_a3 bigint,
    algorithm_run_flag_a4 bigint,
    algorithm_run_flag_a5 bigint,
    algorithm_run_flag_a6 bigint,
    l2_quality_flag_a1 bigint,
    l2_quality_flag_a10 bigint,
    l2_quality_flag_a2 bigint,
    l2_quality_flag_a3 bigint,
    l2_quality_flag_a4 bigint,
    l2_quality_flag_a5 bigint,
    l2_quality_flag_a6 bigint,
    l4_quality_flag_a1 bigint,
    l4_quality_flag_a10 bigint,
    l4_quality_flag_a2 bigint,
    l4_quality_flag_a3 bigint,
    l4_quality_flag_a4 bigint,
    l4_quality_flag_a5 bigint,
    l4_quality_flag_a6 bigint,
    predictor_limit_flag_a1 bigint,
    predictor_limit_flag_a10 bigint,
    predictor_limit_flag_a2 bigint,
    predictor_limit_flag_a3 bigint,
    predictor_limit_flag_a4 bigint,
    predictor_limit_flag_a5 bigint,
    predictor_limit_flag_a6 bigint,
    response_limit_flag_a1 bigint,
    response_limit_flag_a10 bigint,
    response_limit_flag_a2 bigint,
    response_limit_flag_a3 bigint,
    response_limit_flag_a4 bigint,
    response_limit_flag_a5 bigint,
    response_limit_flag_a6 bigint,
    selected_mode_a1 bigint,
    selected_mode_a10 bigint,
    selected_mode_a2 bigint,
    selected_mode_a3 bigint,
    selected_mode_a4 bigint,
    selected_mode_a5 bigint,
    selected_mode_a6 bigint,
    selected_mode_flag_a1 bigint,
    selected_mode_flag_a10 bigint,
    selected_mode_flag_a2 bigint,
    selected_mode_flag_a3 bigint,
    selected_mode_flag_a4 bigint,
    selected_mode_flag_a5 bigint,
    selected_mode_flag_a6 bigint,
    shot_number integer NOT NULL,
    xvar_a1 double precision[],
    xvar_a10 double precision[],
    xvar_a2 double precision[],
    xvar_a3 double precision[],
    xvar_a4 double precision[],
    xvar_a5 double precision[],
    xvar_a6 double precision[],
    agbd_se real,
    agbd_t real,
    agbd_t_se real,
    algorithm_run_flag bigint,
    beam bigint,
    channel bigint,
    degrade_flag bigint,
    delta_time double precision,
    elev_lowestmode real,
    elev_lowestmode_a1 real,
    elev_lowestmode_a10 real,
    elev_lowestmode_a2 real,
    elev_lowestmode_a3 real,
    elev_lowestmode_a4 real,
    elev_lowestmode_a5 real,
    elev_lowestmode_a6 real,
    lat_lowestmode_a1 double precision,
    lat_lowestmode_a10 double precision,
    lat_lowestmode_a2 double precision,
    lat_lowestmode_a3 double precision,
    lat_lowestmode_a4 double precision,
    lat_lowestmode_a5 double precision,
    lat_lowestmode_a6 double precision,
    lon_lowestmode_a1 double precision,
    lon_lowestmode_a10 double precision,
    lon_lowestmode_a2 double precision,
    lon_lowestmode_a3 double precision,
    lon_lowestmode_a4 double precision,
    lon_lowestmode_a5 double precision,
    lon_lowestmode_a6 double precision,
    sensitivity_a1 real,
    sensitivity_a10 real,
    sensitivity_a2 real,
    sensitivity_a3 real,
    sensitivity_a4 real,
    sensitivity_a5 real,
    sensitivity_a6 real,
    stale_return_flag bigint,
    l2_quality_flag bigint,
    l4_quality_flag bigint,
    landsat_treecover double precision,
    landsat_water_persistence bigint,
    leaf_off_doy bigint,
    leaf_off_flag bigint,
    leaf_on_cycle bigint,
    leaf_on_doy bigint,
    pft_class bigint,
    region_class bigint,
    urban_focal_window_size bigint,
    urban_proportion bigint,
    lat_lowestmode double precision,
    lon_lowestmode double precision,
    master_frac double precision,
    master_int bigint,
    predict_stratum text COLLATE pg_catalog."default",
    predictor_limit_flag bigint,
    response_limit_flag bigint,
    selected_algorithm bigint,
    selected_mode bigint,
    selected_mode_flag bigint,
    sensitivity real,
    solar_elevation real,
    surface_flag bigint,
    xvar double precision[],
    geom geometry(Point,4326),
    label text COLLATE pg_catalog."default",
    filename text COLLATE pg_catalog."default" NOT NULL,
    upload_date timestamp without time zone,
    CONSTRAINT gedi_4a_data_complete_pkey PRIMARY KEY (shot_number, filename)
)

TABLESPACE pg_default;

ALTER TABLE public.gedi_4a_data_complete
    OWNER to earthshot;
-- Index: idx_gedi_4a_data_complete_geom

-- DROP INDEX public.idx_gedi_4a_data_complete_geom;

CREATE INDEX idx_gedi_4a_data_complete_geom
    ON public.gedi_4a_data_complete USING gist
    (geom)
    TABLESPACE pg_default;